## Color palette
# Base00 #1b1918
# Base01 #2c2421
# Base02 #68615e
# Base03 #766e6b
# Base04 #9c9491
# Base05 #a8a19f
# Base06 #e6e2e0
# Base07 #f1efee
# Base08 #f22c40
# Base09 #df5320
# Base0A #c38418
# Base0B #7b9726
# Base0C #3d97b8
# Base0D #407ee7
# Base0E #6666ea
# Base0F #c33ff3


[mgr]
marker_copied = { fg = "#7b9726", bg = "#7b9726" }
marker_cut = { fg = "#f22c40", bg = "#f22c40" }
marker_marked = { fg = "#407ee7", bg = "#407ee7" }
marker_selected = { fg = "#df5320", bg = "#df5320" }

cwd = { fg = "#f22c40" }
hovered = { reversed = true }
preview_hovered = { reversed = true }

find_keyword = { fg = "#df5320", bg = "#1b1918" }
find_position = {}

tab_active = { reversed = true }
tab_inactive = {}
tab_width = 1

count_copied = { fg = "#1b1918", bg = "#7b9726" }
count_cut = { fg = "#1b1918", bg = "#c38418" }
count_selected = { fg = "#1b1918", bg = "#f22c40" }

border_symbol = "│"
border_style = { fg = "#407ee7" }


[tabs]
active = { fg = "#407ee7", bg = "reset" }
inactive = { fg = "#1b1918", bg = "#407ee7" }
sep_inner = { open = "", close = "" }
sep_outer = { open = "", close = "" }


[mode]
normal_main = { fg = "#1b1918", bg = "#407ee7" }
normal_alt = { fg = "#407ee7", bg = "#1b1918" }
select_main = { fg = "#1b1918", bg = "#7b9726" }
select_alt = { fg = "#7b9726", bg = "#1b1918" }
unset_main = { fg = "#1b1918", bg = "#f22c40" }
unset_alt = { fg = "#f22c40", bg = "#1b1918" }


[status]
overall = { fg = "#f22c40", bg = "#1b1918" }
sep_left = { open = "", close = "" }
sep_right = { open = "", close = "" }

perm_type = { fg = "#3d97b8" }
perm_read = { fg = "#f22c40" }
perm_write = { fg = "#df5320" }
perm_exec = { fg = "#7b9726" }
perm_sep = { fg = "#6666ea" }

progress_label = { fg = "#407ee7", bg = "#1b1918", bold = true }
progress_normal = { fg = "#7b9726", bg = "#1b1918" }
progress_error = { fg = "#f22c40", bg = "#1b1918" }


[which]
cols = 2
separator = " - "
separator_style = { fg = "#1b1918" }
mask = { bg = "#1b1918" }
rest = { fg = "#1b1918" }
cand = { fg = "#407ee7" }
desc = { fg = "#1b1918" }


[confirm]


[spot]


[notify]
title_info = { fg = "#7b9726" }
title_warn = { fg = "#df5320" }
title_error = { fg = "#f22c40" }


[pick]
border = { fg = "#407ee7" }
active = { fg = "#407ee7", bold = true }
inactive = {}


[input]
border = { fg = "#f22c40" }
title = {}
value = {}
selected = { reversed = true }


[cmp]
border = { fg = "#407ee7" }
active = { reversed = true }
inactive = {}


[tasks]
border = { fg = "#7b9726" }
title = {}
hovered = { fg = "#7b9726" }


[help]
on = { fg = "#6666ea" }
run = { fg = "#3d97b8" }
desc = {}
hovered = { reversed = true, bold = true }
footer = { fg = "#1b1918", bg = "#f22c40" }


[filetype]
rules = [
    # images
    { mime = "image/*", fg = "#df5320" },

    # media
    { mime = "{audio,video}/*", fg = "#6666ea" },

    # archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#c38418" },

    # documents
    { mime = "application/{pdf,doc,rtf,vnd.*}", fg = "#7b9726" },

    # broken links
    { name = "*", is = "orphan", fg = "#f22c40" },

    # executables
    { name = "*", is = "exec", fg = "#7b9726" },

    # fallback
    { name = "*", fg = "#f1efee" },
    { name = "*/", fg = "#407ee7" },
]
